export const ADD_NODE_ROW = "ADD_NODE_ROW";
export const NEW_NODE_NUMBER_CHANGED = "NEW_NODE_NUMBER_CHANGED";
export const NEW_NODE_FORCE_CHANGED = "NEW_NODE_FORCE_CHANGED";
export const CHANGE_NODE = "CHANGE_NODE";
export const REMOVE_NODE_ROW = "REMOVE_NODE_ROW";
export const CHANGING_NODE_NUMBER_CHANGED = "CHANGING_NODE_NUMBER_CHANGED";
export const CHANGING_NODE_FORCE_CHANGED = "CHANGING_NODE_FORCE_CHANGED";
export const CHANGING_NODE_SUBMIT = "CHANGING_NODE_SUBMIT";